[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multiagent-chat"
version = "0.0.1"
description = "Simple MultiAgent Chat System"
requires-python = ">=3.10"
authors = [{name="Anwar Sadad"}]
readme = "README.md"
dependencies = []
